import React from "react";
import Head from "next/head";

export default class Layout extends React.Component<{
    children : React.ReactNode
}, {

}> {
    render() {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    <nav className={styles.navBar}>
                        <div className={styles.topIconContainer}>
                            <Link href={"/"}><i className="fa-sharp fa-solid fa-building-shield"></i></Link>
                            <Link href={"Preference"}><i className="fa-sharp fa-solid fa-handcuffs"></i></Link>
                            {/*<Link href={"/project"}><i className="fas fa-language"></i></Link>*/}
                            {/*<Link href={"/account"}><i className="fas fa-users"></i></Link>*/}

                        </div>

                        <div className={styles.bottomIconContainer}>
                            <i className="fas fa-gear"></i>
                            <i className="fas fa-right-from-bracket"></i>
                        </div>
                    </nav>

                    <div className={styles.rightPagesContainer}>
                        <div className={styles.rightPagesTopContainer}>
                            <img src={lspd} alt={"LSPD"} className={styles.lspdLogo}/>
                        </div>
                        {this.props.children}
                    </div>
                </main>
            </>
        );
    }
}